webui.py
添加基于 Gradio 的 WebUI 供推理使用，需要安装 Gradio。
`pip install gradio`
使用方法
`python webui.py -c <配置文件> -m <模型文件>`
=> Add a webui for Inference (need gradio)

.gitignore, requirements.txt, server.py, utils.py
这样就可以避免安装ffmpeg二进制文件，顺便还支持了ogg格式。
=> feat: use av instead of ffmpeg

attentions.py, text/chinese_bert.py, utils.py, webui.py
这样就不会一启动打印一大堆DEBUG了，顺便改了之前没注意到的 bert 里的 mps。
=> feat: 优化日志打印

infer_utils.py, server.py, webui.py
server.py也有这两个函数，复用一下，避免每次都要更新两遍。
=> Extract get_text() and infer() from webui.py.

bert_gen.py
=> fix bug in bert_gen.py

tools/translate.py, webui.py
=> Fix bug in translate.py

bert/bert-large-japanese-v2/vocab.txt, server.py
功能新增：
+ 支持加载多版本模型
+ 支持加载多个模型
api变更：
+ 使用`model`指定模型，类型`int`，为在`config.yml`中`server`加载模型的顺序，从零开始
+ 使用`speaker_id`指定说话人id，类型`int`，与`speaker`必须指定其一
=> Update server.py. 支持多版本多模型

re_matching.py, webui.py
=> 增加一个按钮，点击后可以按句子切分，添加“|”

re_matching.py, webui.py
撤销了添加停顿的按钮
非常非常抱歉，我犯了个错误，上次提交的webui里的``` slicer.click(
cut_sent,
inputs=[text],
outputs=[text],
)```里的cut_sent应为```re_matching.cut_sent```
以及代码也许需要优化一下
=> 加入整合包管理器的特性：长文本合成可以自定义句间段间停顿

infer.py, server.py, webui.py
=> Refactor: reusing model loading in webui.py and server.py.

emo_gen.py
=> Change emo_gen.py

webui.py
1.小修复：删除上次忘记删除的按钮
2.可选启动参数，指定模型和配置文件，不填从全局配置读取
3.可以通过上传文本文件切分生成
=> fix and update

server_fastapi.py
=> Update server_fastapi.py. Sort models by trained steps.

server_fastapi.py
=> Update server_fastapi.py. Allowed to search models in "./"

server_fastapi.py
=> Update server_fastapi.py. Add new api endpoints.

webui.py
Fixed the problem of volume inconsistency between sentence segments caused by Gradio volume normalization
=> [Fix] Fix Volume inconsistent

server_fastapi.py, tools/log.py, tools/translate.py
更新后端，为了方便对比相同模型，在模型路径相同时不再重复加载，而是改为添加引用。log美化
=> Update server_fastapi.py. Avoid loading the model repeatedly. Add logger

bert/bert_models.json, bert_gen.py, config.py, default_config.yml, text/__init__.py, text/bert_utils.py, text/chinese_bert.py, text/english_bert_mock.py, text/japanese_bert.py, webui.py
- `bert_gen.py`：通过`huggingface_hub`自动下载`./bert/`里面缺失的模型
=> Auto download missing model for `bert_gen.py`

text/japanese.py
=> 修复部分日文汉字无法被推理/训练

config.py, default_config.yml, train_ms.py, utils.py
- `train_ms.py`: 自动下载`config.yml`中指定的底模
=> Add model download to `train_ms.py`

infer.py, server_fastapi.py, tools/translate.py
=> Fix: server_fastapi.py, support auto split

infer.py, oldVersion/V101/__init__.py
=> Fix: Add missing torch.cuda.empty_cache()

commons.py, data_utils.py, default_config.yml
Reverts fishaudio/Bert-VITS2#165
=> Revert "Fix slice segments GPU perf"

server_fastapi.py
fastapi中的get与post的api复用相同的推理函数，修正之前的切分生成的静音错误
=> 复用相同逻辑，修正静音添加错误

utils.py
1. `load_model(model_path, config_path)`函数：
- 功能：加载模型。
- 参数：
- `model_path`：模型文件的路径。
- `config_path`：配置文件的路径。
- 返回值：加载后的模型对象。
2. `mix_model(network1, network2, output_path, voice_ratio=(.5,.5), tone_ratio=(.5,.5))`函数：
- 功能：混合两个模型并保存为新模型。
- 参数：
- `network1`：第一个模型对象。
- `network2`：第二个模型对象。
- `output_path`：保存混合模型的路径。
- `voice_ratio`（可选）：声音比例，默认为（0.5, 0.5）。
- `tone_ratio`（可选）：语调比例，默认为（0.5, 0.5）。
- 返回值：无。
```python
from utils import load_model, mix_model
model_clara = load_model('./logs/clara/clara.pth', './logs/clara/config.json') # 日语女生，低语
model_otto = load_model('./logs/otto/G_11200.pth', './logs/otto/config.json') # 中文男声，有点东北口音
model_taffy = load_model('./logs/Taffy/G_15800.pth', './logs/Taffy/config.json') # 中文女声，高亢，咬字不清
model_carol = load_model('./logs/Carol/G_12600.pth', …
```
=> feat: add voice mix and tone mix

emotion_clustering.py
快速分类音频并把yml格式结果存在训练根目录里，之后webui推理时可以快速调取参考音频
=> 快速分类音频并把yml格式结果存在训练根目录里

server_fastapi.py
=> fix server_fastapi.py: 修复bug。

bert_gen.py, models.py, train_ms.py
=> Fix duration discriminator

hiyoriUI.py
=> Feat: hiyoriUI.py. 支持2.3版本以及auto、mix模式

text/japanese.py
reduce constant,
and ... easy to extend :)
=> optimize hiragana2p time complexity

requirements.txt, text/chinese.py
https://github.com/fishaudio/fish-speech/issues/21
优化中文文本的规范化，之前规范化做的不对可能对底模训练也有一些负面影响
=> optimize chinese text normalization

text/japanese.py, text/japanese_mora_list.py
- Fix Japanese accent bug
- Change phone of `ん` from `n` to `N`
=> Fix and refactor japanese g2p

config.py, default_config.yml, g2pW/pypinyin_G2pW_bv2/g2pw.py, infer.py, text/chinese.py, train_ms.py, utils.py
训练一晚上起来看tensorboard里20000step的效果好但是50000多的全出不了声，但是留下的模型只剩50000多的了，只好重头来。
写了这个让别人少走弯路
=> 保存部分ckpt，而不是只保存最新的

train_ms.py
fix the bug for https://github.com/fishaudio/Bert-VITS2/commit/81e034b1b7e0937262eae82e6f30b640e2776bb3
=> fix args parser for train_ms

webui_preprocess.py
User can use double semicolon to make shell injection
=> Fix CVE-2024-39685
